# Generated by Django 5.1.4 on 2025-02-11 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='ex. facebook', max_length=100)),
                ('total_follower', models.IntegerField(default=0, help_text='foolowers or subscribers etc.')),
                ('account_link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='whatsapp phone number written in international format withou plus sign ex. 254740562740', max_length=25)),
                ('total_followers', models.IntegerField(default=0, help_text='accross all your social platforms')),
                ('total_points', models.IntegerField(default=0)),
                ('brief_bio', models.TextField(blank=True)),
                ('type_of_content', models.TextField(blank=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('reffered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refferal', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('social_media_accounts', models.ManyToManyField(blank=True, to='creators.socialmediaaccount')),
            ],
        ),
    ]
