# Generated by Django 5.1.4 on 2025-02-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='not_willing_to_patner',
            field=models.BooleanField(default=False, help_text='checking if creator is willing to go in patnership'),
        ),
        migrations.AddField(
            model_name='creator',
            name='not_willing_to_work',
            field=models.BooleanField(default=False, help_text='checking if creators is willing to create content for businesses on monthly retainor'),
        ),
        migrations.AddField(
            model_name='creator',
            name='willing_to_patner',
            field=models.BooleanField(default=False, help_text='checking if creator is willing to go in patnership'),
        ),
        migrations.AddField(
            model_name='creator',
            name='willing_to_work',
            field=models.BooleanField(default=False, help_text='checking if creators is willing to create content for businesses on monthly retainor'),
        ),
    ]
