# Generated by Django 5.1.4 on 2025-03-20 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_creator_not_willing_to_patner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMonetization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_login_progress', models.FloatField()),
                ('login_update_date', models.DateField(auto_now=True)),
                ('challenge_participation_progress', models.FloatField()),
                ('challenge_participation_update_date', models.DateField(auto_now=True)),
                ('average_percentage_progress', models.IntegerField(default=0)),
                ('monetizable', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creators.creator')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorsSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_one', models.TextField(default='Are you open to working for brands to shoot videos, pictures or livestreams?')),
                ('question_one_answer', models.BooleanField(default=False)),
                ('question_two', models.TextField(default='Rate your video creation skills from 1-10?')),
                ('question_two_answer', models.IntegerField(default=1)),
                ('question_three', models.TextField(default='Which video creation tools stack you are currently using?')),
                ('question_three_answer', models.TextField(blank=True)),
                ('question_four', models.TextField(default='Which video creation tools stack you think if you have you can create more awsome videos?')),
                ('question_four_answer', models.TextField(blank=True)),
                ('question_five', models.TextField(default='Which business industries or categories are you passionate to creating videos for? list as many as you can')),
                ('question_five_answer', models.TextField(blank=True)),
                ('question_six', models.TextField(default='Add a youtube or any social media link to a video you created')),
                ('question_six_answer', models.URLField(blank=True, null=True)),
                ('question_seven', models.TextField(default='Add another youtube or any social media link to a video you created')),
                ('question_seven_answer', models.URLField(blank=True, null=True)),
                ('question_eight', models.TextField(default='Add a third youtube or any social media link to a video you created')),
                ('question_eight_answer', models.URLField(blank=True, null=True)),
                ('question_nine', models.TextField(default='Current Country of residence')),
                ('question_nine_answer', models.CharField(default='Kenya', max_length=200)),
                ('question_ten', models.TextField(default='Current County of residence')),
                ('question_ten_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('question_eleven', models.TextField(default='Minimum weekly pay you are open to?')),
                ('question_eleven_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creators.creator')),
            ],
        ),
    ]
