# Generated by Django 5.1.4 on 2025-03-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_accountmonetization_creatorssurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmonetization',
            name='average_percentage_progress',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='accountmonetization',
            name='challenge_participation_progress',
            field=models.FloatField(default=3.334),
        ),
        migrations.AlterField(
            model_name='accountmonetization',
            name='challenge_participation_update_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accountmonetization',
            name='login_update_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accountmonetization',
            name='percentage_login_progress',
            field=models.FloatField(default=1.667),
        ),
    ]
