# Generated by Django 5.1.4 on 2025-03-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0005_alter_creatorssurvey_question_five_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorssurvey',
            name='question_13',
            field=models.TextField(default='Can you do livestream too?'),
        ),
        migrations.AddField(
            model_name='creatorssurvey',
            name='question_13_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
