# Generated by Django 5.1.4 on 2025-03-24 13:05

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0007_alter_creatorssurvey_question_13_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='brief_bio',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='type_of_content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='creatorssurvey',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='creators.creator'),
        ),
        migrations.AlterField(
            model_name='creatorssurvey',
            name='question_eleven',
            field=models.TextField(default='Minimum monthly pay you are open to?'),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='total_follower',
            field=models.IntegerField(default=0, help_text='followers or subscribers etc.'),
        ),
    ]
