# Generated by Django 5.1.4 on 2025-04-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0008_alter_creator_brief_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='phone_number',
            field=models.CharField(blank=True, help_text='whatsapp phone number written in international format withou plus sign ex. 254740562740', max_length=25, null=True),
        ),
    ]
