# Generated by Django 5.1.4 on 2025-03-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.CharField(choices=[('challenge', 'challenge'), ('view reward program', 'view reward program')], default='challenge', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='maximum_payout_per_creator',
            field=models.IntegerField(default=0, help_text='setting maximum payout for view reward program helps pay ceators to a certain number of view after which extra views you wont pay for'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='pay_per_1000_views',
            field=models.IntegerField(default=10, help_text='how much are you paying for 100 views'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='target_winners',
            field=models.IntegerField(default=7, help_text='how many winners do you want for this challenge'),
        ),
    ]
