# Generated by Django 5.1.4 on 2025-03-20 10:55

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_challenge_category_and_more'),
        ('creators', '0007_alter_creatorssurvey_question_13_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCreationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('photo shooting', 'photo shooting'), ('video creation', 'video creation'), ('livestreaming', 'livestreaming'), ('both photo shooting, video creation, livestreaming', 'both photo shooting, video creation, livestreaming')], max_length=150)),
                ('job_description', tinymce.models.HTMLField(blank=True)),
                ('monthly_pay', models.IntegerField(default=10000)),
                ('number_of_creators', models.IntegerField(default=10000, help_text='number of creators you target to hire')),
                ('position_filled', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='businesses.business')),
                ('creators', models.ManyToManyField(blank=True, to='creators.creator')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_by_business', models.BooleanField(default=False)),
                ('accepted_by_creator', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creators.creator')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.contentcreationjob')),
            ],
        ),
    ]
