# Generated by Django 5.1.4 on 2025-03-24 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_contentcreationjob_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcreationjob',
            name='job_type',
            field=models.CharField(choices=[('photo shooting', 'photo shooting'), ('video creation', 'video creation'), ('livestreaming', 'livestreaming'), ('photo shooting, video creation, livestreaming', 'photo shooting, video creation, livestreaming')], max_length=150),
        ),
        migrations.AlterField(
            model_name='contentcreationjob',
            name='number_of_creators',
            field=models.IntegerField(default=4, help_text='number of creators you target to hire'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='businesses.contentcreationjob'),
        ),
    ]
