# Generated by Django 5.1.4 on 2025-04-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_alter_challenge_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='instant_reward',
            field=models.CharField(blank=True, help_text="it's the reward you give creator immediately after participating", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='target_winners',
            field=models.IntegerField(default=7, help_text='how many winners do you want for this challenge'),
        ),
    ]
